// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_getSignal
List c_getSignal(std::string bam_file, std::string binned_region, std::string seqname, int start, int end, StringVector rg_name, StringVector rg_KS, StringVector rg_FO);
RcppExport SEXP _torrentSignal_c_getSignal(SEXP bam_fileSEXP, SEXP binned_regionSEXP, SEXP seqnameSEXP, SEXP startSEXP, SEXP endSEXP, SEXP rg_nameSEXP, SEXP rg_KSSEXP, SEXP rg_FOSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bam_file(bam_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type binned_region(binned_regionSEXP);
    Rcpp::traits::input_parameter< std::string >::type seqname(seqnameSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< StringVector >::type rg_name(rg_nameSEXP);
    Rcpp::traits::input_parameter< StringVector >::type rg_KS(rg_KSSEXP);
    Rcpp::traits::input_parameter< StringVector >::type rg_FO(rg_FOSEXP);
    rcpp_result_gen = Rcpp::wrap(c_getSignal(bam_file, binned_region, seqname, start, end, rg_name, rg_KS, rg_FO));
    return rcpp_result_gen;
END_RCPP
}
// idxstats_pbam
int idxstats_pbam(std::string bam_file, int n_threads_to_use);
RcppExport SEXP _torrentSignal_idxstats_pbam(SEXP bam_fileSEXP, SEXP n_threads_to_useSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bam_file(bam_fileSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads_to_use(n_threads_to_useSEXP);
    rcpp_result_gen = Rcpp::wrap(idxstats_pbam(bam_file, n_threads_to_use));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_torrentSignal_c_getSignal", (DL_FUNC) &_torrentSignal_c_getSignal, 8},
    {"_torrentSignal_idxstats_pbam", (DL_FUNC) &_torrentSignal_idxstats_pbam, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_torrentSignal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
