# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_getSignal <- function(bam_file, binned_region, seqname, start, end, rg_name, rg_KS, rg_FO) {
    .Call(`_torrentSignal_c_getSignal`, bam_file, binned_region, seqname, start, end, rg_name, rg_KS, rg_FO)
}

idxstats_pbam <- function(bam_file, n_threads_to_use = 1L) {
    .Call(`_torrentSignal_idxstats_pbam`, bam_file, n_threads_to_use)
}

